CREATE TABLE `donations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `status` varchar(64) NOT NULL,
  `email` varchar(256) NOT NULL,
  `donation_amount` int(11) NOT NULL,
  `donation_spread` text NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ipn_track_id` varchar(256) NOT NULL,
  `txn_id` varchar(256) NOT NULL,
  `nick` varchar(256) NOT NULL,
  `nick_url` varchar(1024) NOT NULL,
  `payer_id` varchar(256) NOT NULL,
  `address_street` varchar(512) NOT NULL,
  `address_zip` varchar(512) NOT NULL,
  `address_country_code` varchar(512) NOT NULL,
  `address_name` varchar(512) NOT NULL,
  `address_country` varchar(512) NOT NULL,
  `address_city` varchar(512) NOT NULL,
  `address_state` varchar(512) NOT NULL,
  `payment_date` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `IP` varchar(64) NOT NULL,
  `donation_type` varchar(64) NOT NULL,
  `newsletter_email` varchar(512) NOT NULL,
  `logo_url` varchar(1024) NOT NULL,
  `txn_type` varchar(256) NOT NULL,
  `full_report` varchar(4096) NOT NULL,
  KEY `id` (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=65 DEFAULT CHARSET=latin1$$